[[endpoint]]
name = "Golang.org"
url = "http://www.golang.org/"
timeout = 1000

[[endpoint]]
name = "Google"
url = "http://www.google.com/"
timeout = 1000

[[endpoint]]
name = "Non-existant domain"
url = "http://www.somestupidname.com/"
timeout = 1000

[[endpoint]]
name = "BBC News"
url = "http://www.bbc.co.uk/news"
timeout = 1000

[[endpoint]]
name = "XKCD"
url = "http://www.xkcd.com/"
timeout = 1000

[[endpoint]]
name = "File not found"
url = "https://github.com/fatih/saijgs"
timeout = 1000