[[endpoint]]
name = "Golang.org"
url = "https://golang.org/"
timeout = 1000

[[endpoint]]
name = "Google UK"
url = "https://www.google.co.uk/"
timeout = 1000

[[endpoint]]
name = "Non-existant"
url = "http://www.somestupidname.com/"
timeout = 1000

[[endpoint]]
name = "BBC News"
url = "http://www.bbc.co.uk/news"
timeout = 1000

[[endpoint]]
name = "XKCD"
url = "http://www.xkcd.com/"
timeout = 1000

[[endpoint]]
name = "File not found"
url = "https://github.com/fatih/saijgs"
timeout = 1000

[[endpoint]]
name = "Server 503"
url = "http://httpstat.us/503"
timeout = 1000

[[endpoint]]
name = "Server 301"
url = "http://httpstat.us/301"
timeout = 1000

[[endpoint]]
name = "Delayed timeout"
url = "http://www.deelay.me/2000/https://www.google.co.uk"
timeout = 1000

[[endpoint]]
name = "Delayed"
url = "http://www.deelay.me/2000/https://www.google.co.uk"
timeout = 10000
